---
# This playbook deploys  Cassandra and Spark on Red Hat Linux Flavour: CentOS 6. 

- hosts: cassandras 
  accelerate: "{{ accelerate }}"
  gather_facts: false
  user: clusterconfig
  sudo: true
  roles:    
      - java

- hosts: cassandras 
  accelerate: "{{ accelerate }}"
  gather_facts: false
  user: clusterconfig
  sudo: true
  roles:    
      - cassandras




